version: '3.8'

services:
  scanner:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - clamav-db:/var/lib/clamav
    environment:
      - NODE_ENV=production
      - PORT=3000

volumes:
  clamav-db: 